name: Linters
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          workdir: api
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile

  mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install node modules
        run: |
          cd mobile
          npm ci

      - name: tsc
        run: |
          cd mobile
          npx tsc

      - name: eslint
        run: |
          cd mobile
          npx eslint
